app/investing/strategies/urls.py
from django.urls import path

from . import views

app_name = "investing.strategies"

urlpatterns = [
    path("", views.index, name="index"),
    path("nasdaq-monthly/<int:pk>", views.nasdaq_monthly, name="nasdaq-monthly"),
]

app/investing/urls.py
from django.contrib import admin
from django.urls import path, include
from investing.core.views import UserLoginView, UserRegistrationView
from investing.strategies.views import index

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", index, name="home"),
    path("strategie/", include("investing.strategies.urls", namespace="strategies")),
    path(
        "accounts/login/",
        UserLoginView.as_view(),
        name="login",
    ),
    path(
        "accounts/register/",
        UserRegistrationView.as_view(),
        name="django_registration_register",
    ),
    path("accounts/", include("django_registration.backends.one_step.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
]

app/investing/strategies/models.py
from django.db import models
from django.utils.translation import gettext as _


class StrategyType(models.Model):
    """
    Model for strategy types
    """

    name = models.CharField(_("Name"), max_length=300)
    id = models.IntegerField(_("Id"), primary_key=True)


class Strategy(models.Model):
    """
    Model for strategy
    """

    name = models.CharField(_("Name"), max_length=300)
    setup = models.JSONField(_("setup"))
    type = models.ForeignKey(
        StrategyType, verbose_name=_("Strategy type"), on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class StrategyCalculationResult(models.Model):
    """
    Model for stocks info
    """

    strategy = models.ForeignKey(Strategy, on_delete=models.CASCADE)
    date = models.DateField(_("Date"))
    kontext_filter_result = models.BooleanField(_("Kontext filter result"))
    filter_result = models.JSONField(_("Filter result"))

    def __str__(self):
        return self.strategy.name + " " + str(self.date)

app/investing/strategies/forms.py
from crispy_forms.bootstrap import FormActions
from crispy_forms.helper import FormHelper
from crispy_forms.layout import HTML, Div, Layout, Submit
from django import forms
from django.forms import HiddenInput
from django.utils.translation import gettext as _


class SearchStrategyCalculationForm(forms.Form):
    search_date = forms.DateField(
        label=_("Date of calculation"),
        widget=forms.DateInput(
            attrs={"data-provide": "datepicker", "autocomplete": "off"}
        ),
    )
    money_investest = forms.FloatField(
        label=_("Money to invest"),
        widget=forms.TextInput(attrs={"inputmode": "numeric", "pattern": "[0-9]*"}),
    )
    leverage = forms.FloatField(label=_("Leverage"), widget=forms.TextInput())
    companies_to_buy = forms.IntegerField(
        label=_("Number of companies to buy"), widget=forms.TextInput(),
    )

    def __init__(self, *args, **kwargs):
        super(SearchStrategyCalculationForm, self).__init__(*args, **kwargs)
        self.fields["search_date"].readonly = True
        self.helper = FormHelper(self)
        self.helper.layout = Layout(
            Div(
                Div(
                    Div(
                        Div(
                            HTML(_("Strategy calculation")),
                            css_class="app-fx app-left",
                        ),
                        css_class="card-header",
                    ),
                    Div(
                        Div(
                            Div("search_date", css_class="col-sm-3"),
                            Div("money_investest", css_class="col-sm-3"),
                            Div("leverage", css_class="col-sm-3"),
                            Div("companies_to_buy", css_class="col-sm-3"),
                            css_class="row",
                        ),
                    ),
                    Div(FormActions(Submit("save", "Search",),), css_class="mt-3",),
                    css_class="",
                ),
                css_class="",
            ),
        )

app/investing/strategies/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
import logging

import pandas as pd
import json

from .models import StrategyCalculationResult, Strategy
from .forms import SearchStrategyCalculationForm
from .tables import StrategyTable


logger = logging.getLogger(__name__)

# Create your views here.
@login_required
@require_http_methods(["GET"])
def index(request):

    return render(request, "strategies/index.html")

@login_required
@require_http_methods(["GET", "POST"])
def nasdaq_monthly(request, pk):
    table_django = {}
    if request.method == "POST":
        form = SearchStrategyCalculationForm(request.POST)
        if form.is_valid():
            logger.debug("Form is valid")
            request_date = form.cleaned_data["search_date"]
            money_per_company = (
                form.cleaned_data["money_investest"]
                * form.cleaned_data["leverage"]
                / form.cleaned_data["companies_to_buy"]
            )
            table = StrategyCalculationResult.objects.get(
                strategy=pk, date=request_date
            ).filter_result
            #table_json = json.loads(table)
            df = pd.DataFrame.from_dict(
                    table, orient="index", dtype=float
                )
            logger.debug(df)
            table_django = StrategyTable(
                df.to_dict("records"),
                money_per_company=money_per_company,
                count=form.cleaned_data["companies_to_buy"],
            )
    else:
        form = SearchStrategyCalculationForm()
    strategy = Strategy.objects.get(pk=pk)
    strategy_dates = []
    for i in StrategyCalculationResult.objects.filter(strategy=pk).values_list(
        "date", flat=True
    ):
        strategy_dates.append(i.strftime("%d-%m-%Y"))
    return render(
        request,
        "strategies/strategy_result.html",
        {
            "strategy": strategy,
            "strategy_dates": strategy_dates,
            "form": form,
            "table_django": table_django,
        },
    )


app/investing/strategies/templates/strategies/index.html
{% extends "base_logged_in.html" %}
{% load static %}
{% load i18n %}


{% block title %}Moje Strategie{% endblock %}

{% block content %}
  <div class="app-entity-strategie">
    {% include "strategies/toolbar_strategie.html"%}
    <div class="row app-entity-cards mb-3">
      <div class="col">
        <a href="{% url 'strategies:nasdaq-monthly' '1' %}" class="card app-card-entity app-entity-strategie app-card-nasdaq-strategie">
          <div class="card-body">
            <img src="{% static 'img/logo-am-mark.png' %}" />
          </div>
          <div class="card-footer">
            {% trans "Nasdaq mesacna" %}
          </div>
        </a>
      </div>
    </div>
  </div>
  <div class="app-card-desc-wrapper">
    <div class="app-collapse-nasdaq-strategie collapse">
      <div class="p-3">
        <h4>{% trans "Nasdaq mesacna strategie" %}</h4>
        <hr />
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
      </div>
    </div> 
    
  </div>


  <script>
      $(".app-card-entity").mouseleave(function(){
        $(".app-collapse-nasdaq-strategie").hide(100);
      });
      $(".app-card-entity").mouseover(function(){
        $(".app-collapse-nasdaq-strategie").show(100);
      });
  </script>
{% endblock %}

app/investing/strategies/templates/strategies/strategy_result.html
{% extends "base_logged_in.html" %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load django_tables2 %}

{% block title %}{{strategy.name}}{% endblock %}

{% block content %}
  <div class="app-entity-strategie">
    {% include "strategies/toolbar_strategie.html"%}
    <div>
    {% crispy form %}
    {% if table_django %}{% render_table table_django %}{%endif%}
    
    </div>
  </div>
  
  {{strategy_dates|json_script:"dates" }}
  <script src="{% static '/js/datepicker-dates.js' %}"></script>

{% endblock %}

app/investing/strategies/templates/strategies/toolbar_strategie.html
{% load i18n %}

<div class="app-toolbar">
  <div class="app-left">
    <div class="app-entity-title">
      <a href="{% url 'strategies:index' %}"><span class="material-icons">dynamic_feed</span> Strategie</a>
    </div>
    <div id="id-app-entity-item" class="app-entity-item">
    </div>
  </div>
</div>